sudo: required
services:
  - docker
before_install:
  - docker build -t rollocasanova/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true rollocasanova/docker-react npm run test
language: generic
